### ISSUE TITLE
Crash and...

### ISSUE THREAD

**Issue by JukoiDev** [Jefff000/darklight-csgo#2]

**Comment by JukoiDev** [comment]
Ignore my post up ^
Cheat is crashing:
1. On release when opening menu
2. On debug when clicking RETRY to debug cheat.

![Przechwytywanie](https://user-images.githubusercontent.com/79868869/137750347-d4626ddc-2865-419b-be2b-603cb41b1395.PNG)

**Comment by PowerfullPower** [comment]
> Ignore this, we are running a botnet on your computer- much love.
> 
> On a serious note, could you please provide some debug information regarding the crash so we can investigate this.

please update on latest version of csgo :/ or can u give fix?
